"commit_message": "[ci skip]"

files:
  - source: /src/common/managesieve.ui/i18n/en-US.json
    translation: /src/common/managesieve.ui/i18n/%locale%.json
  - source: /src/common/libSieve/i18n/en-US.json
    translation: /src/common/libSieve/i18n/%locale%.json
  - source: /src/wx/_locales/en_US/messages.json
    translation: /src/wx/_locales/%locale_with_underscore%/%original_file_name%
